<?php

define('FIELD_NAME', 'field_geo_code_1');

/*
 * Implement hook_enable()
 */
function civicrm_address_geocode_enable() {
  civicrm_initialize();
  /**
   * Create a geofield.
   */
  $field = array(
    'field_name' => FIELD_NAME,
    'type' => 'geofield',
  );
  field_create_field($field);

  /**
   * Bind field to a entity bundle.
   */
  $instance = array(
    'label' => 'Geo Code',
    'field_name' => $field['field_name'],
    'entity_type' => 'civicrm_address',
    'bundle' => 'civicrm_address',
    'widget' => array(
      'type' => 'geocoder',
    ), 
  );
  field_create_instance($instance);

  $params = array(
    'geocode' => 1,
    'parse' => 0, // Set this to 1 if you want to parse addresses.
    'throttle' => 1,
  );
  $gc = new CRM_Utils_Address_BatchUpdate($params);
  $result = $gc->run();
  if ($result['is_error'] == 1) {
    drupal_set_message(t($result['messages']), 'error');
  }
}

/**
 * Implements hook_disable().
 *
 * Remove field from civicrm_address bundle and then delete the field.
 */
function civicrm_address_geocode_disable() {
  $instance = array(
    'label' => 'Geo Code',
    'field_name' => FIELD_NAME,
    'entity_type' => 'civicrm_address',
    'bundle' => 'civicrm_address',
  );
  field_delete_instance($instance);
  field_delete_field($instance['field_name']);
  print 'Removed ' . $instance['label'] . "\n";
}

/*
 * Implement hook_form_alter()
 */
function civicrm_address_geocode_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'civicrm_address_form' && isset($form[FIELD_NAME])) {
    $form[FIELD_NAME]['#disabled'] = TRUE;
    return $form;
  }
}

/*
 * Implement hook_civicrm_postProcess()
 */
function civicrm_address_geocode_civicrm_postProcess($formName, &$form) {
  if ($formName == "CRM_Contact_Form_Contact") {
    $ids = array();
    // Get address ID (Possibly, Ids considering more than one address for multiple location types) 
    if (!empty($form->_values['address'])) {
      foreach ($form->_values['address'] as $key => $value) {
        $ids[$key] = $value['id'];
      }
    }
    if (!empty($form->_submitValues['address'])) {
      $address = civicrm_api3('Address', 'get', array('contact_id' => $form->_contactId));
      foreach ($address['values'] as $k => $v) {
        $g = makePoint($v['geo_code_1'], $v['geo_code_2']);
        savePoint($k, $g);
      }
    }
    // Now get submitted geofield values
    $geofield = array();
    if (!empty($form->_submitValues['address']) && !empty($ids)) {
      foreach ($form->_submitValues['address'] as $k => $v) {
        if (empty($v['geo_code_1']) || empty($v['geo_code_2'])) {
          continue;
        }
        $geofield[$k] = makePoint($v['geo_code_1'], $v['geo_code_2']);
      }
    }
    if (!empty($geofield) && !empty($ids)) {
      foreach ($ids as $i => $id) {
        savePoint($id, $geofield[$i]);
      }
    }
  }
}

function updateGeoCode($address) {
  if (!empty($address->geo_code_1) && !empty($address->geo_code_2)) {
    $geofield = makePoint($address->geo_code_1, $address->geo_code_2);
    savePoint($address->id, $geofield);
  }
}

function makePoint($lat, $lon) {
  return array(
    'geom' => "POINT ($lon $lat)",
    'geo_type' => 'point',
    'lat' => $lat . "000000",
    'lon' => $lon . "000000",
    'left' => $lon . "000000",
    'top' => $lat . "000000",
    'right' => $lon . "000000",
    'bottom' => $lat . "000000"
  );
}

function savePoint($id, $geofield) {
  $name = FIELD_NAME;
  $entity = entity_load_single('civicrm_address', $id);
  $entity->{$name}[LANGUAGE_NONE][0] = $geofield;
  field_attach_update('civicrm_address', $entity);
}

function civicrm_address_geocode_views_query_alter(&$view, &$query) {
    $join = new views_join();
    $join->table = 'civicrm_contact';
    $join->field = 'id';
    $join->left_table = 'civicrm_address';
    $join->left_field = 'contact_id';
    $join->type = 'LEFT';
    $query->add_relationship('civicrm_contact', $join, 'civicrm_address');
}

/**
 * Implements hook_views_api().
 */
function civicrm_address_geocode_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_views_data_alter().
 */
function civicrm_address_geocode_views_data_alter(&$data) {
  $data['civicrm_address']['last_name']['title'] = 'Last Name';
  $data['civicrm_address']['last_name']['help'] = 'Last Name';
  $data['civicrm_address']['last_name']['filter']['handler'] = 'civicrm_address_geocode_handler_filter_last_name';
}